// flow-typed signature: 20146f0cc37126d57d3be1f6661f5c1d
// flow-typed version: <<STUB>>/express-fileupload_v^1.1.5/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-fileupload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-fileupload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-fileupload/example/server' {
  declare module.exports: any;
}

declare module 'express-fileupload/lib/fileFactory' {
  declare module.exports: any;
}

declare module 'express-fileupload/lib/index' {
  declare module.exports: any;
}

declare module 'express-fileupload/lib/isEligibleRequest' {
  declare module.exports: any;
}

declare module 'express-fileupload/lib/memHandler' {
  declare module.exports: any;
}

declare module 'express-fileupload/lib/processMultipart' {
  declare module.exports: any;
}

declare module 'express-fileupload/lib/processNested' {
  declare module.exports: any;
}

declare module 'express-fileupload/lib/tempFileHandler' {
  declare module.exports: any;
}

declare module 'express-fileupload/lib/utilities' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/fileFactory.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/fileLimitUploads.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/multipartFields.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/multipartUploads.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/options.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/processNested.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/server' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/tempFile.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/utilities.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-fileupload/example/server.js' {
  declare module.exports: $Exports<'express-fileupload/example/server'>;
}
declare module 'express-fileupload/lib/fileFactory.js' {
  declare module.exports: $Exports<'express-fileupload/lib/fileFactory'>;
}
declare module 'express-fileupload/lib/index.js' {
  declare module.exports: $Exports<'express-fileupload/lib/index'>;
}
declare module 'express-fileupload/lib/isEligibleRequest.js' {
  declare module.exports: $Exports<'express-fileupload/lib/isEligibleRequest'>;
}
declare module 'express-fileupload/lib/memHandler.js' {
  declare module.exports: $Exports<'express-fileupload/lib/memHandler'>;
}
declare module 'express-fileupload/lib/processMultipart.js' {
  declare module.exports: $Exports<'express-fileupload/lib/processMultipart'>;
}
declare module 'express-fileupload/lib/processNested.js' {
  declare module.exports: $Exports<'express-fileupload/lib/processNested'>;
}
declare module 'express-fileupload/lib/tempFileHandler.js' {
  declare module.exports: $Exports<'express-fileupload/lib/tempFileHandler'>;
}
declare module 'express-fileupload/lib/utilities.js' {
  declare module.exports: $Exports<'express-fileupload/lib/utilities'>;
}
declare module 'express-fileupload/test/fileFactory.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/fileFactory.spec'>;
}
declare module 'express-fileupload/test/fileLimitUploads.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/fileLimitUploads.spec'>;
}
declare module 'express-fileupload/test/multipartFields.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/multipartFields.spec'>;
}
declare module 'express-fileupload/test/multipartUploads.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/multipartUploads.spec'>;
}
declare module 'express-fileupload/test/options.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/options.spec'>;
}
declare module 'express-fileupload/test/processNested.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/processNested.spec'>;
}
declare module 'express-fileupload/test/server.js' {
  declare module.exports: $Exports<'express-fileupload/test/server'>;
}
declare module 'express-fileupload/test/tempFile.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/tempFile.spec'>;
}
declare module 'express-fileupload/test/utilities.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/utilities.spec'>;
}
