// flow-typed signature: 786eb146d32c254b922a1020ba03d8c5
// flow-typed version: <<STUB>>/onesignal-node_v^2.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'onesignal-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'onesignal-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'onesignal-node/lib/client' {
  declare module.exports: any;
}

declare module 'onesignal-node/lib/constants' {
  declare module.exports: any;
}

declare module 'onesignal-node/lib/index' {
  declare module.exports: any;
}

declare module 'onesignal-node/lib/notification' {
  declare module.exports: any;
}

declare module 'onesignal-node/test/client.test' {
  declare module.exports: any;
}

declare module 'onesignal-node/test/mocks/client' {
  declare module.exports: any;
}

declare module 'onesignal-node/test/mocks/notification' {
  declare module.exports: any;
}

declare module 'onesignal-node/test/notification.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'onesignal-node/lib/client.js' {
  declare module.exports: $Exports<'onesignal-node/lib/client'>;
}
declare module 'onesignal-node/lib/constants.js' {
  declare module.exports: $Exports<'onesignal-node/lib/constants'>;
}
declare module 'onesignal-node/lib/index.js' {
  declare module.exports: $Exports<'onesignal-node/lib/index'>;
}
declare module 'onesignal-node/lib/notification.js' {
  declare module.exports: $Exports<'onesignal-node/lib/notification'>;
}
declare module 'onesignal-node/test/client.test.js' {
  declare module.exports: $Exports<'onesignal-node/test/client.test'>;
}
declare module 'onesignal-node/test/mocks/client.js' {
  declare module.exports: $Exports<'onesignal-node/test/mocks/client'>;
}
declare module 'onesignal-node/test/mocks/notification.js' {
  declare module.exports: $Exports<'onesignal-node/test/mocks/notification'>;
}
declare module 'onesignal-node/test/notification.test.js' {
  declare module.exports: $Exports<'onesignal-node/test/notification.test'>;
}
