// flow-typed signature: 1f55b7d9a6e088c5e90b9bcc324288a2
// flow-typed version: <<STUB>>/pogi_v^2.5.16/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pogi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pogi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pogi/lib/bin/generateInterface' {
  declare module.exports: any;
}

declare module 'pogi/lib/index' {
  declare module.exports: any;
}

declare module 'pogi/lib/pgConverters' {
  declare module.exports: any;
}

declare module 'pogi/lib/pgDb' {
  declare module.exports: any;
}

declare module 'pogi/lib/pgDbOperators' {
  declare module.exports: any;
}

declare module 'pogi/lib/pgSchema' {
  declare module.exports: any;
}

declare module 'pogi/lib/pgTable' {
  declare module.exports: any;
}

declare module 'pogi/lib/pgUtils' {
  declare module.exports: any;
}

declare module 'pogi/lib/queryAble' {
  declare module.exports: any;
}

declare module 'pogi/lib/queryWhere' {
  declare module.exports: any;
}

declare module 'pogi/spec/run' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pogi/lib/bin/generateInterface.js' {
  declare module.exports: $Exports<'pogi/lib/bin/generateInterface'>;
}
declare module 'pogi/lib/index.js' {
  declare module.exports: $Exports<'pogi/lib/index'>;
}
declare module 'pogi/lib/pgConverters.js' {
  declare module.exports: $Exports<'pogi/lib/pgConverters'>;
}
declare module 'pogi/lib/pgDb.js' {
  declare module.exports: $Exports<'pogi/lib/pgDb'>;
}
declare module 'pogi/lib/pgDbOperators.js' {
  declare module.exports: $Exports<'pogi/lib/pgDbOperators'>;
}
declare module 'pogi/lib/pgSchema.js' {
  declare module.exports: $Exports<'pogi/lib/pgSchema'>;
}
declare module 'pogi/lib/pgTable.js' {
  declare module.exports: $Exports<'pogi/lib/pgTable'>;
}
declare module 'pogi/lib/pgUtils.js' {
  declare module.exports: $Exports<'pogi/lib/pgUtils'>;
}
declare module 'pogi/lib/queryAble.js' {
  declare module.exports: $Exports<'pogi/lib/queryAble'>;
}
declare module 'pogi/lib/queryWhere.js' {
  declare module.exports: $Exports<'pogi/lib/queryWhere'>;
}
declare module 'pogi/spec/run.js' {
  declare module.exports: $Exports<'pogi/spec/run'>;
}
